services:
  - type: web
    name: leaderforge-langgraph
    runtime: node
    plan: free
    rootDir: agent
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health