/**
 * File: apps/web/app/api/agent/context/route.ts
 * Purpose: Agent-native endpoint for context discovery and UI schema generation
 * Owner: Engineering Team
 * Tags: #api #agent-native #context #ui-schema
 */

import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { restoreSession } from '../../../lib/supabaseServerClient';
import { createContextResolutionAgent } from 'agent-core/agents/ContextResolutionAgent';

/**
 * POST /api/agent/context
 * Agent-native endpoint that determines what context/UI to show based on user entitlements.
 * Returns a complete UI schema generated by agents, not hardcoded database lookups.
 */
export async function POST(req: NextRequest) {
  const startTime = Date.now();
  console.log('[API] POST /api/agent/context - agent-native context discovery');

  try {
    // Parse request body
    const requestBody = await req.json().catch(() => ({}));
    const userMessage = requestBody.message || 'What should I see on my dashboard?';
    const requestedContext = requestBody.context || 'leaderforge';
    console.log('[API] Request body:', JSON.stringify(requestBody, null, 2));

        // WORKAROUND: Since middleware validates auth, try headers directly
    const cookieHeader = req.headers.get('cookie') || '';
    console.log('[API] Raw cookie header:', cookieHeader.length > 0 ? 'present' : 'missing');

    // Extract project ref for cookie name
    const projectRef = process.env.NEXT_PUBLIC_SUPABASE_URL?.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1];
    const authCookieName = `sb-${projectRef}-auth-token`;

    // Parse cookies from header
    const cookies_from_header = cookieHeader.split(';').reduce((acc, cookie) => {
      const [name, value] = cookie.trim().split('=');
      if (name && value) {
        acc[name] = decodeURIComponent(value);
      }
      return acc;
    }, {} as Record<string, string>);

    console.log('[API] Cookies from header:', Object.keys(cookies_from_header).join(', '));
    console.log('[API] Auth cookie found in header:', !!cookies_from_header[authCookieName]);

    // Try both methods
    const cookieStore = await cookies();
    let { session, supabase } = await restoreSession(cookieStore);

    // FALLBACK: If restoreSession fails but middleware validated auth, use header cookies
    if (!session && cookies_from_header[authCookieName]) {
      console.log('[API] 🔄 restoreSession failed, trying header fallback...');

      try {
        // Parse the auth cookie from headers (ADR-0031 array format)
        const authData = JSON.parse(cookies_from_header[authCookieName]);

        // Handle ADR-0031 array format: [access_token, null, refresh_token, null, null]
        const accessToken = Array.isArray(authData) ? authData[0] : authData.access_token;
        const refreshToken = Array.isArray(authData) ? authData[2] : authData.refresh_token;

        if (accessToken && refreshToken) {
          console.log('[API] ✅ Header fallback: Found valid auth data (array format)');
          // Create a mock session since middleware already validated it
          session = {
            access_token: accessToken,
            refresh_token: refreshToken,
            user: { id: 'middleware-validated' }, // Placeholder since middleware validated
            expires_at: Date.now() + 3600000, // 1 hour from now
            expires_in: 3600,
            token_type: 'bearer'
          };
        }
      } catch (headerError) {
        console.log('[API] ❌ Header fallback failed:', headerError);
      }
    }

    if (!session?.user) {
      console.log('[API] No authenticated session found');
      return NextResponse.json({
        error: 'Unauthorized',
        details: 'Authentication required for context discovery'
      }, { status: 401 });
    }

    const userId = session.user.id;
    console.log('[API] ✅ Authenticated user:', userId);

    // Agent-native: Use ContextResolutionAgent to orchestrate entire context discovery
    const agent = createContextResolutionAgent(supabase);
    const contextResult = await agent.resolveUserContexts({
      userId,
      tenantKey: requestedContext,
      userMessage,
      includePreferences: true
    });

    // Build response with agent-generated context in the format CopilotKitProvider expects
    const agentResponse = {
      success: true,
      context: {
        systemInstructions: contextResult.systemInstructions,
        appliedContexts: contextResult.appliedContexts,
        userPreferences: contextResult.userPreferences,
        metadata: {
          ...contextResult.metadata,
          responseTime: Date.now() - startTime,
          userMessage,
          requestedContext,
          contextId: `context_${Date.now()}`
        }
      }
    };

    const endTime = Date.now();
    const duration = endTime - startTime;

    console.log(`[API] Agent-generated context schema returned in ${duration}ms`);

    return NextResponse.json(agentResponse, {
      status: 200,
      headers: {
        'X-Response-Time': `${duration}ms`,
        'X-Cache-Status': 'agent-generated',
        'Cache-Control': 'no-store', // Don't cache agent responses
      }
    });

  } catch (error) {
    const err = error as Error;
    const endTime = Date.now();
    const duration = endTime - startTime;

    console.error(`[API] Agent context discovery failed (${duration}ms):`, err);
    return NextResponse.json({
      error: 'Agent context discovery failed',
      details: err.message
    }, { status: 500 });
  }
}